### PR TITLE
chore: update organisms list for 2024-09-20 (#89)

### PR DESCRIPTION
**Pull request by hunterckx**

### CODE REVIEW

**Comment by NoopDog** [comment]
Hi @hunterckx do you know why we are seeing only the 692 and not the 702 assemblies on the organism list? Thanks!

**Comment by hunterckx** [comment]
@NoopDog I believe it's because there are 10 assemblies that have no matches in the genomes spreadsheet

**Comment by NoopDog** [comment]
Thanks can you add the IDs of the extra tracks ( the ones that are missing in the sheet) to this ticket? @hunterckx

**Comment by hunterckx** [comment]
@NoopDog Alright, I've added a comment to #89 with the IDs

**Review by NoopDog — APPROVED** [review]

**Pull request merged**
